name: CI

on:
  workflow_dispatch:
  
  # schedule:
  # - cron: '31 * * * *'

jobs:
  Groovy:
    runs-on: ubuntu-latest
    container: ghcr.io/1bah/dynam:groovy-basic

    steps:
      - name: Launch
        run: /home/groovy/groovy_verify.sh 4 300
