name: CI

on:
  # workflow_dispatch:
  
  schedule:
  - cron: '10 * * * *'

jobs:
  Groovy:
    runs-on: ubuntu-latest
    container: ghcr.io/1bah/dynam:groovy-basic

    steps:
      - name: Launch
        run: |
          cd /home/groovy
          ls
          ./groovy_verify.sh 4 300
